### ISSUE TITLE
无法显示数据啊

### ISSUE THREAD

**Issue by iamckun** [LeiShi1313/downloader-exporter#12]
![image](https://user-images.githubusercontent.com/65990499/215329345-2971bf85-5593-45da-9c55-b18a68084f20.png)
有大佬知道是啥原因吗
![image](https://user-images.githubusercontent.com/65990499/215329381-6aa27fee-bb46-447f-9a46-6f53075d4b9d.png)
这里有一点显示

**Comment by LeiShi1313** [comment]
多等会
